"""initial

Revision ID: b1804c33b481
Revises: 
Create Date: 2026-04-02 23:42:40.677800

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b1804c33b481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_session_pkey'))
    )
    op.create_index(op.f('chat_session_client_id_idx'), 'chat_session', ['client_id'], unique=True)
    op.create_table('chat_conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('flow_type', sa.Enum('BASIC', 'DBOS', 'TEMPORAL', 'DBOS_REPLAY', name='flow_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('preview', sa.String(length=255), nullable=True),
    sa.Column('active_replay_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('chat_conversation_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_conversation_pkey'))
    )
    op.create_index(op.f('chat_conversation_session_id_idx'), 'chat_conversation', ['session_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('ui_message_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_messages_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('chat_message_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_pkey')),
    sa.UniqueConstraint('conversation_id', 'sequence', name='chat_message_conversation_id_sequence_key')
    )
    op.create_index(op.f('chat_message_conversation_id_idx'), 'chat_message', ['conversation_id'], unique=False)
    op.create_table('chat_thread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('flow_type', sa.Enum('BASIC', 'DBOS', 'TEMPORAL', 'DBOS_REPLAY', name='flow_type'), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('dbos_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('task_queue', sa.String(length=255), nullable=True),
    sa.Column('replay_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('chat_thread_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_thread_pkey')),
    sa.UniqueConstraint('conversation_id', name='chat_thread_conversation_id_key')
    )
    op.create_index(op.f('chat_thread_conversation_id_idx'), 'chat_thread', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chat_thread_conversation_id_idx'), table_name='chat_thread')
    op.drop_table('chat_thread')
    op.drop_index(op.f('chat_message_conversation_id_idx'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('chat_conversation_session_id_idx'), table_name='chat_conversation')
    op.drop_table('chat_conversation')
    op.drop_index(op.f('chat_session_client_id_idx'), table_name='chat_session')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
