"""chat_conversation_message_schema

Revision ID: 63f31954a072
Revises: 
Create Date: 2026-04-03 19:01:32.916261

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '63f31954a072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flow_type', sa.Enum('basic', 'dbos', 'temporal', 'dbos-replay', name='flow_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('preview', sa.String(length=255), nullable=True),
    sa.Column('active_replay_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_conversation_pkey'))
    )
    op.create_index(op.f('chat_conversation_flow_type_idx'), 'chat_conversation', ['flow_type'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('ui_message_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_messages_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('chat_message_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_pkey')),
    sa.UniqueConstraint('conversation_id', 'sequence', name='chat_message_conversation_id_sequence_key')
    )
    op.create_index(op.f('chat_message_conversation_id_idx'), 'chat_message', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chat_message_conversation_id_idx'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('chat_conversation_flow_type_idx'), table_name='chat_conversation')
    op.drop_table('chat_conversation')
    # ### end Alembic commands ###
